name: make

on:
  pull_request:          # PR into master (=release)
    branches:
      - master
  pull_request_target:   # PR (from fork) into develop.   
    branches:            # Uses workflow defined in base, not in fork.
      - develop
  workflow_dispatch:     # to trigger workflow manually

jobs:
  make_test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Clean up
      run: make clean
      
    - name: Build
      run: make

    - name: Run tests
      run: make test
